#!/usr/bin/env bash
set -eu -o pipefail

# shellcheck source=./sdcard_function.inc.sh
source "$(dirname "$0")/sdcard_function.inc.sh"

declare SSID=
declare PSK=

if [[ "$#" -eq 0 ]]; then
    cat <<EOF
Usage:
  "$0 SSID PSK"

EOF
else
    SSID="${1}"
    PSK="${2:-}"
fi

WPA_SUPPLICANT="$(mktemp)"
if [[ -n "$SSID" ]]; then
    cat > "${WPA_SUPPLICANT}" <<EOF
country=US
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1

network={
    ssid="$SSID"
    psk="$PSK"
}
EOF
    sed -i -e '/^ *psk=""/d' "${WPA_SUPPLICANT}"
fi


function enable_ssh_and_wifi(){
    BOOT_VOLUME="$(mount | grep -E "^${SDCARD}s1 " | cut -d' ' -f3)"
    echo "Found boot at $BOOT_VOLUME"
    if [[ -f "${BOOT_VOLUME}/ssh" ]]; then
        echo "${BOOT_VOLUME}/ssh has been exist."
    else
        touch "${BOOT_VOLUME}/ssh"
        echo "${BOOT_VOLUME}/ssh created."
    fi

    if test -n "$SSID" && cp "${WPA_SUPPLICANT}" "${BOOT_VOLUME}/wpa_supplicant.conf"; then
        echo "${BOOT_VOLUME}/wpa_supplicant.conf created."
    fi
}

run enable_ssh_and_wifi
