#!/usr/bin/env bash
set -eu -o pipefail

source "$(dirname "$0")/sdcard_function.inc.sh"

RASPBERRY_IMG="${1:-}"
if test -z "$RASPBERRY_IMG"; then
    echo "Usage: $0 raspberry.img"
    exit 1
fi

function gen_write_sdcard_command() {
    local SDCARD="$1"
    echo "dd bs=1M if=\"$RASPBERRY_IMG\" of=\"$SDCARD\" conv=sync"
}

RASPBERRY_IMG=/tmp/foo.img gen_write_sdcard_command /dev/disk9\
    | grep -E '^dd bs=1M if="/tmp/foo.img" of="/dev/disk9" conv=sync$' >/dev/null

if ! test -f "$RASPBERRY_IMG"; then
    echo "$RASPBERRY_IMG not exist."
    exit 1
fi

if [[ "$(id -u)" -ne 0 ]]; then
    sudo "$0" "$@"
    exit $?
fi

function write_raspberry_img() {
    diskutil info "$SDCARD"

    for _LOOP in $(seq 15 -1 1); do
        echo -n "Will write to $SDCARD after $_LOOP seconds. Press Ctrl-C if you want to break."$'\r'
        sleep 1 || exit 2
    done

    echo -e "\nWriting to SD card $SDCARD ..."
    du -h "$RASPBERRY_IMG"
    echo "Press Ctrl-T to show the writing progress, the size of image is $(stat --printf='%s' "$RASPBERRY_IMG")"
    diskutil unmountDisk "$SDCARD"
    gen_write_sdcard_command "$SDCARD" | time bash -x

    sleep 2
}

run write_raspberry_img
