- name: Ensure samba
  apt: name=samba,smbclient,samba-common-bin

- name: Ensure share folders
  file: path="{{ item.path }}" state=directory owner="{{ item.valid_users }}"
  with_items: "{{ samba_shares }}"

- name: Ensure samba configuration
  template: src=smb.conf.j2 dest=/etc/samba/smb.conf
  notify: Restart samba

- name: Create samba user
  shell: |
    if ! pdbedit -L | grep "^{{ item.name }}" 2>&1 > /dev/null; then
      (echo {{ item.password }}; echo {{ item.password }}) | smbpasswd -s -a {{ item.name }}
      umask 077
      echo "{{ item.name }} {{ item.password }}" > "/etc/samba/password-{{ item.name }}"
    fi
  args:
    creates: "/etc/samba/password-{{ item.name }}"
  with_items: "{{ samba_users }}"
