#!/bin/bash
set -e

EMPTY_FEATURE_TGZ="$(cd "$(dirname "$0")"; pwd)/empty_feature.tgz"
if [[ -d features ]]; then
    echo "Error: there is a 'features' in the current directory."
    exit 1
else
    tar -zxf "$EMPTY_FEATURE_TGZ"
fi

echo "Done: 'features' created."
