#!/bin/bash
set -e
wp post update $(wp post list --post_type=post,page --format=ids) --comment_status=open
wp option set default_comment_status open

cat <<EOF

comment textarea: comment
   submit button: Post Comment

EOF
echo Done.
