#!/bin/bash
set -e
WPUSER="$1"
WPUSERPASSWD="${2:-${WPUSER}1234}"
if [[ -z "$WPUSER" ]]; then
    echo "Usage:"
    echo "    $(basename "$0") username [new_password]"
    exit 1
fi

wp user update "$WPUSER" --user_pass="$WPUSERPASSWD"
