#!/bin/bash
set -e
if [[ -z "$1" ]]; then
    echo "Usage:"
    echo "    $(basename "$0") user@example.com"
    exit 1
fi

COMMENT_IDS="$(wp comment list --format=ids --author_email="$1")"
[[ -z "$COMMENT_IDS" ]] || wp comment delete $COMMENT_IDS --force

echo Done.
