#!/bin/bash
set -e
if [[ -z "$1" ]]; then
    echo "Usage:"
    echo "    $(basename "$0") user@example.com"
    exit 1
fi
wp comment delete $(wp comment list --format=ids --author_email="$1") --force

echo Done.
