#!/bin/bash
set -eu -o pipefail

if [[ "$#" -eq 0 ]]; then
    cat <<-EOF
		Usage:
		    $0 <display_id>

		Example:
		    $0 42
		EOF
fi

VNC_DISPLAY_ID="$1"

VNCSERVER=/usr/bin/vncserver
VNCSERVER_ARGS=":$VNC_DISPLAY_ID -geometry {{ vnc_geometry }}"

if [[ ! -f "$HOME/.vnc/passwd" ]]; then
    mkdir -p "$HOME/.vnc/passwd"
    echo "{{ vnc_passwd }}" | vncpasswd -f > "$HOME/.vnc/passwd"
    chmod go-rwx "$HOME/.vnc/passwd"
fi

$VNCSERVER $VNCSERVER_ARGS || exit 0

cd $HOME/.vnc
websockify --web /usr/share/novnc $((8900 + VNC_DISPLAY_ID)) localhost:$((5900 + VNC_DISPLAY_ID))
